[project]
name = "project-av"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "capstone>=5.0.3",
    "pefile>=2024.8.26",
    "python-magic>=0.4.27",
    "yara-python>=4.5.1",
]
